name: CI process of Linting

on:
  pull_request:
    branches: "develop"
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn lint
